name: Sync with Upstream
on: 
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Sync Repo
        run: gh repo sync ${{ github.repository }} -b main
        env:
          GH_TOKEN: ${{ secrets.PAT }}
